language: python
python:
  - "2.7"
  - "3.6"      # current default Python on Travis CI
before_install:
  - python --version
  - pip install -U pip
  - python setup.py install
  - pip install -U pytest
  - pip install codecov
script:
  #- py.test --cov-report term-missing --cov library/ test/units/library/  -v
  - py.test test/units/library/test_addition.py  -v
after_success:
  - codecov